tugas/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import update_status.urls as update_status
import add_friend.urls as add_friend
import dashboard.urls as dashboard
import profile_page.urls as profile_page

urlpatterns = [
    url(r'^add_friend/', include(add_friend, namespace='add_friend')),
    url(r'^admin/', admin.site.urls),
    url(r'^update_status/', include(update_status, namespace='update-status')),
    url(r'^dashboard/', include(dashboard, namespace='dashboard')),
    url(r'^profile_page/', include(profile_page, namespace='profile_page')),
    url(r'^$', RedirectView.as_view(url='dashboard/', permanent=True), name='index'),

]

update_status/urls.py
from django.conf.urls import url
from .views import index, add_status, clear
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_status', add_status, name='add_status'),
    #url(r'^add_comment', comment, name='add_comment'),
    url(r'^clear/(?P<object_id>[0-9]+)', view=clear, name='clear')
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="description" content="Tugas 1">
    <meta name="author" content="{{author}}">
    <meta name="style" content="{{style}}">
    <!-- bootstrap csss -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/add_friend.css' %}" />


    <style>
        body{
                background-size: cover;
                min-height: 100vh;
            }

            *{
                color: white;
            }
        {% if style == 1 %}
            body{
                background: linear-gradient(to bottom, #80361f, #000000) no-repeat;
            }

            *{
                font-family: "Open Sans","Montserrat","Segoe UI", "Calibri","Arial","Times New Roman","sans-serif";
            }
        {% else %}
            body{
                    background: linear-gradient(to bottom, #38b1ff, #1514ee) no-repeat;
                }

                *{
                    font-family: "Segoe UI", "Calibri","Arial","Times New Roman","sans-serif";
                }

        {% endif %}
    </style>


    <title>
        {% block title %} Tugas 1 By {{author}}{% endblock %}
    </title>
</head>

<body>
    <header>
        {% include "header.html" %}
    </header>
    <br></br>
    <br></br>
    <content>
        <div class="container">
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
        </div>

    </content>
    <footer style="bottom: 0">
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

templates/footer.html
<p style="margin-top: 50px ; text-align: center">&copy; {{author}}</p>

templates/header.html
<head>
    <meta name="style" content="{{style}}">
</head>

<style>
    {% if style == 1 %}

        .navbar-default{
            background-color: #80361f;
            border-color: transparent;
        }

        .navbar-default .navbar-brand{
            color : wheat;
        }

        .navbar-default .navbar-brand:hover{
            color : white;
        }

        .navbar-default .navbar-nav > li > a{
            color: wheat;
        }

        .navbar-default .navbar-nav > li > a:hover{
            color: white;
        }

    {% else %}

        .navbar-default{
            background-color: #38b1ff;
            border-color: transparent;
        }

        .navbar-default .navbar-brand{
            color : #1f1f1f;
        }

        .navbar-default .navbar-brand:hover{
            color : black;
        }

        .navbar-default .navbar-nav > li > a{
            color: #1f1f1f;
        }

        .navbar-default .navbar-nav > li > a:hover{
            color: black;
        }
    {% endif %}
</style>


<!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-static-top navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'dashboard:index' %}">Home</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'update-status:add_status' %}"> Status </a></li>
            <li><a href="{% url 'profile_page:index' %}"> Profile </a></li>
            <li><a href="{% url 'add_friend:index' %}"> Friends </a></li>
            <li><a href="{% url 'dashboard:index' %}"> Stats </a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>