dashboard/urls.py
from django.conf.urls import url
from .views import index, changeStyle

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'changeStyle', changeStyle, name="changeStyle")
]

tugas/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import update_status.urls as update_status
import add_friend.urls as add_friend
import dashboard.urls as dashboard
import profile_page.urls as profile_page

urlpatterns = [
    url(r'^add_friend/', include(add_friend, namespace='add_friend')),
    url(r'^admin/', admin.site.urls),
    url(r'^update_status/', include(update_status, namespace='update-status')),
    url(r'^dashboard/', include(dashboard, namespace='dashboard')),
    url(r'^profile_page/', include(profile_page, namespace='profile_page')),
    url(r'^$', RedirectView.as_view(url='dashboard/', permanent=True), name='index'),

]

update_status/urls.py
from django.conf.urls import url
from .views import index, add_status, clear
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_status', add_status, name='add_status'),
    #url(r'^add_comment', comment, name='add_comment'),
    url(r'^clear/(?P<object_id>[0-9]+)', view=clear, name='clear')
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render
from update_status.models import Status
from add_friend.models import Friend
from templates.UserData import name, author
from datetime import *
from django.http import HttpResponseRedirect


response = {"style": 1}

def index(request):
    feedsAmount = Status.objects.count()
    if feedsAmount > 0:
        latestFeed = Status.objects.all()[feedsAmount-1]
        message = latestFeed.status
        time = latestFeed.created_date
    else:
        message = "This user has not posted anything"
        time = date(datetime.now().year,datetime.now().month,datetime.now().day)

    friendAmount = Friend.objects.count()

    response['author'] =  author
    response['name'] =  name
    response['friendsAmount'] =  friendAmount
    response['feedsAmount'] =  feedsAmount
    response['latestFeed'] =  message
    response['created'] =  time

    return render(request, 'dashboard_page.html', response)

def changeStyle(request):
    response["style"] = abs(response["style"]-1)
    return HttpResponseRedirect('/dashboard/')

dashboard/templates/dashboard_page.html
{% extends "base.html" %}

    {% block content %}
    {% load staticfiles %}

        <style>
        .profile-img {
        background-image: url('http://www.dorkadia.com/wp-content/uploads/2013/05/2432714-threeronecdeadspace3.jpg');
        background-size:cover;
        background-position: center;
        background-repeat:no-repeat;
        margin: auto;
        }

        #centered{
            text-align: center;
        }

        .latest-feed{
            width: auto;
            height: auto;
        }

        .zoomable{
            font-size: 100%;
            transition-duration: .5s;
        }

        .zoomable:hover{
            font-size: 150%;
            transition-duration: .5s;
        }

        p{
            font-size: 15px;
        }

        hr{
            border-color: white;

        }

        .clickable{
            color: white;
            transition-duration: .5s;
        }

        .clickable:hover{
            color: #c1642d;
            transition-duration: .5s;
        }
        </style>

        <h1 style="text-align: center">
            <a  href="{% url 'add_friend:index' %}"> <b class="clickable">{{ name }}</b> </a>
        </h1>

        <div class="profile-img img-circle" style="width: 250px ; height: 250px"></div>


        <div id = "centered" >
            <p style="font-size: 20px">
                <br/>
                {{ friendsAmount }} <a  href="{% url 'add_friend:index' %}"> <b class="clickable">Friends</b> </a> | {{ feedsAmount }} <a   href="{% url 'update-status:add_status' %}"> <b class="clickable">Feeds</b> </a>
                <br/>
            </p>
        </div>

        <hr size="30"/>

        <br/>


        <p style="font-size: 25px">Latest Feed<br/></p>
        <div class="card bg-dark border-dark mb-3" style="max-width: 50rem;">
            <div class = "latest-feed card-body">
                <div class="card-header">
                    <div class="profile-img" style="width: 50px ; height: 50px; display:inline-block ; vertical-align: middle; margin-right: 10px"></div>
                    <div style="display: inline-block;">
                        <p style="vertical-align: bottom">{{ name }}</p>
                    </div>
                </div>
                <div class="card-text">
                    <p style="margin-top: 15px; margin-bottom: 3px">
                        {{ latestFeed }}
                    </p>
                    <p style="font-size: 12px">
                       <em>{{ created }}</em>
                    </p>
                </div>
            </div>
        </div>

        <br/>

        <div style="text-align: center">
        <a href="{%url 'dashboard:changeStyle' %}" class="btn btn-default" role="button">Change Style</a>
        </div>

    {% endblock %}