tugas/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import update_status.urls as update_status
import add_friend.urls as add_friend
import dashboard.urls as dashboard
import profile_page.urls as profile_page

urlpatterns = [
    url(r'^add_friend/', include(add_friend, namespace='add_friend')),
    url(r'^admin/', admin.site.urls),
    url(r'^update_status/', include(update_status, namespace='update-status')),
    url(r'^dashboard/', include(dashboard, namespace='dashboard')),
    url(r'^profile_page/', include(profile_page, namespace='profile_page')),
    url(r'^$', RedirectView.as_view(url='dashboard/', permanent=True), name='index'),

]

update_status/urls.py
from django.conf.urls import url
from .views import index, add_status, clear
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_status', add_status, name='add_status'),
    #url(r'^add_comment', comment, name='add_comment'),
    url(r'^clear/(?P<object_id>[0-9]+)', view=clear, name='clear')
]

update_status/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
	status = models.TextField()
	created_date = models.DateTimeField(auto_now_add=True)

# class StatusExp(models.Model):
# 	status = models.TextField()
# 	created_date = models.DateTimeField(auto_now_add=True)
# 	slug = models.SlugField(unique=True)

# 	def get_absolute_url(self):
# 		return ('update_status',(), {'slug' :self.slug})

# 	def save(self, *args, **kwargs):
# 		if not self.slug:
# 			self.slug = slugify(self.title)
# 		super(StatusExp, self).save(*args, **kwargs)

class Comment(models.Model):
	name = models.TextField()
	comment = models.TextField()

# class CommentExp(models.Model):
# 	name = models.CharField(max_length=42)
# 	text = models.TextField()
# 	post = models.ForeignKey(Status)
# 	created_on = models.DateTimeField(auto_now_add=True)

update_status/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    description_attrs = {
        'type': 'text',
        'cols': 135,
        'rows': 4,
        'class': 'todo-form-textarea',
        'placeholder':'What are you feeling today?'
    }

    status = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

class Comment_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    attrs = {
        'class': 'form-control',
        'cols': 100,
        'rows': 2,
    }

    name = forms.CharField(label='Name', required=False, max_length=27, empty_value='Anonymous', widget=forms.Textarea(attrs=attrs))
    comment = forms.CharField(label='Comment', required=True, widget=forms.Textarea(attrs=attrs))

# class CommentForm(forms.ModelForm):
#     class Meta:
#         model = Comment
#         exclude = ['post']

update_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Status_Form
from .models import Status
from templates.UserData import name,author
from dashboard.views import response as from_dashboard

response = {}

def index(request):
    response['name'] = name
    response['author'] = author
    status = Status.objects.all().order_by('-created_date')
    response['status'] = status
    html = 'update_status/update_status.html'
    response['status_form'] = Status_Form
    response["style"] = from_dashboard["style"]
    return render(request, html, response)


def add_status(request):
    form = Status_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['status'] = request.POST['status']
        status = Status(status=response['status'])
        status.save()
        return HttpResponseRedirect('/update_status/')
    else:
        return HttpResponseRedirect('/update_status/')

response = {}
# def comment(request):
#     comment = Comment.objects.all()
#     response['comment'] = comment
#     html = 'update_status/add_comment.html'
#     response['comment_form'] = Comment_Form
#     return render(request, html, response)

# def add_comment(request):
#     form = Comment_Form(request.POST or None)
#     if(request.method == 'POST' and form.is_valid()):
#         response['name'] = request.POST['name'] if request.POST['name'] != "" else "Anonymous"
#         response['comment'] = request.POST['comment']
#         comment = Comment(name=response['name'], comment=response['comment'])
#         comment.save()
#         html ='update_status/add_comment.html'
#         return render(request, html, response)
#     else:        
#         return HttpResponseRedirect('/update_status/')

def clear(request,object_id):
    clearing = Status.objects.get(pk=object_id)
    clearing.delete()
    return HttpResponseRedirect('/update_status/')

# def view_post(request, slug):
#     post = get_object_or_404(StatusExp, slug=slug)
#     form = CommentForm(request.POST or None)
#     if form.is_valid():
#         comment = form.save(commit=False)
#         comment.post = post
#         comment.save()
#         return redirect(request.path)
#     return render_to_response('update_status/add_comment.html',
#                               {
#                                   'post': post,
#                                   'form': form,
#                               },
#                               context_instance=RequestContext(request))

update_status/templates/update_status/add_comment.html
{% extends "base.html" %}

{% block content %}
<div class="container">
<h1> Add Comment</h1>
<section name="input-comment" id="input-comment">
<form id="form" method="POST" action="{% url 'update-status:add_comment' %}" style="color: black">
  <h2></h2>
    {% csrf_token %}
    {{ comment_form }}
    <br>
    <p align=center><input id="submit" type="submit" class="btn btn-danger" value="Post" role="button" style="width:500px"> <a href="/update_status/" class="btn btn-danger" style="width:500px" role="button">Cancel</a></p>
    <br><br><br><br>
    <br>
</form>
</section>

<section name="my-comment" id="my-comment">
  <div class="container">
          {% for j in comment %}
          <div class="comment_box">
                <p style="font-size: 30px">{{j.name}}</p>
                <p> {{j.comment}} </p>   
            </div>
              <br>
            </div>       
          {% endfor %}
    </div>
</section>
</div>
{% endblock %}

update_status/templates/update_status/update_status.html
{% extends "base.html" %}

{% block content %}

<style>
        #form{
        }
        #submit{
            width: 100px;
            align-self: right;
        }
        .profile-img {
        background-image: url('http://www.dorkadia.com/wp-content/uploads/2013/05/2432714-threeronecdeadspace3.jpg');
        background-size:cover;
        background-position: center;
        background-repeat:no-repeat;
        margin: auto;
        }
        .status{
            background-color: rgba(0, 0, 0, 0.4);
            padding: 15px 0 10px 0;
        }
        .status_box{
            margin-left: -10px;
            width: auto;
            margin-right: 15px;
        }
</style>
<h1>UPDATE STATUS</h1>

<section name="input-status" id="input-status">
<form id="form" method="POST" action="{% url 'update-status:add_status' %}" style="color: black ; width: auto">
 	<h2></h2>
    {% csrf_token %}
    {{ status_form }}
    <br>
    <input id="submit" type="submit" class="btn btn-lg btn-block btn-basic" value="Post" style="float:right">
    <br><br><br><br>
    <br>
</form>
</section>

<section name="my-status" id="my-status">
	<div class="container">
        	{% for i in status %}
        	<div class="status_box">
        		<div class="profile-img img-circle" style="width: 70px ; height: 70px;display:inline-block ; vertical-align: middle; "></div>
                <div class="delete" data-id="{{i.id}}" style="display: inline-block;float:right;margin-top: 30px;margin-right: 20px">
                    <a href="{%url 'update-status:clear' object_id=i.id %}" style="float:right"><img src="http://cdn.mysitemyway.com/etc-mysitemyway/icons/legacy-previews/icons/matte-red-and-white-square-icons-business/122923-matte-red-and-white-square-icon-business-trashcan3.png" style="width: 50px;height: 50px"></a>
                </div>
            <div style="display: inline-block; margin-top: auto; margin-bottom: auto; vertical-align: middle">
                <p style="font-size: 30px;margin-left: 20px">{{ name }}</p>
                <p style="margin-left: 20px"> {{i.created_date}} </p>   
            </div>
            <br><br>
            	<div class="status" style="padding:15px 15px 15px 15px"><p> {{i.status}} </p></div>
            	<br>
<!--                 <form action="/update_status/add_comment">
                    <p align=right><input type="submit" class="btn btn-danger" value="Comment" /></p>
                </form> -->
            	<br>
            </div>       
        	{% endfor %}
    </div>
</section>
{% endblock %}